-- 用户表
create table s_user(
    id             varchar(64) generated by default as identity, --主键
    login_name      varchar(64) not null,
    username       varchar(64) not null,
    password       varchar(255) not null,
    salt           varchar(64) not null,
    email          varchar(255),
    register_date   timestamp,
    status         varchar(64),
    primary key (id)
);